version: '3'
volumes:
  postgres:
    driver: local
  redis:
    driver: local

services:

  crowd_ai:
    build:
      context: .
    entrypoint: /app/entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:10.3
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'