source 'https://rubygems.org'
#source 'https://rails-assets.org'
source 'http://insecure.rails-assets.org' # something wrong with Rails assets

# Rails assets gems
gem 'rails-assets-isInViewport'
gem 'rails-assets-jQuery-File-Upload'

ruby '2.5.1'
gem 'rails', '5.2.0'

gem 'active_model_serializers'
gem 'activeadmin'
gem 'authtrail'
gem 'aws-sdk', '~> 2.2'
gem 'bootsnap'
gem 'browser'
gem 'carrierwave', '~> 1.0'
gem 'cells-rails'
gem 'cells'
gem 'cells-erb'
gem 'cookies_eu'
gem 'cocoon'
gem 'country_select'
gem 'codemirror-rails'
gem 'crowdai_admin'
#gem 'crowdai_admin', path: '/Users/sean/src/crowdai/crowdai_admin'
gem 'client_side_validations'
gem 'coffee-rails'
gem 'compass-rails'
gem 'devise'
gem 'doorkeeper', '~> 5.0.0.rc1'
gem 'erbse', '0.1.1'
gem 'excon'
gem 'friendly_id', '~> 5.1.0'
gem 'fast_blank'
gem 'font-awesome-rails'
gem 'figaro'
gem 'fog'
gem 'file_validators'
gem 'gibbon'
gem 'httparty'
gem 'informant-rails'
gem 'include_media_rails'
gem 'inline_svg'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder'
gem 'jquery-atwho-rails'
gem 'kramdown'
gem 'kaminari'
gem 'lodash-rails'
gem 'loofah', '~> 2.2.1'
gem 'maxminddb'
gem 'mandrill-api'
gem 'momentjs-rails', '~> 2.9'
gem 'mini_magick'
gem 'merit'
gem 'net-ssh'
gem 'oj', '~> 3.0'
gem 'paloma', '~> 5.1.0'
gem 'paper_trail'
gem 'pg'
gem 'puma'
gem 'puma_worker_killer'
gem 'pundit'
gem 'prometheus-client'
gem 'remotipart'
gem 'ransack'
gem 'rouge'
gem 'rollbar'
gem 'rubyzip', '~> 1.2.2'
gem 'rails-html-sanitizer', '~> 1.0.4'
gem 'sanitize', '~> 4.6.3'
gem 'simple_enum'
gem 'scenic', '~> 1.3'
gem 'sprockets', '~> 4.0.0.beta8'
gem 'social-share-button'
gem 'sass-rails'
gem 'skylight', '~> 3.0'
gem 'sidekiq', '~> 5.1.1'
gem 'sidekiq-cron', '~> 0.6.3'
gem 'sidekiq-history'
gem 'sidekiq-failures'
gem 'sidekiq-unique-jobs'
gem 'sinatra', '~> 2.0.2', :require => nil
gem 'therubyracer', platforms: :ruby
gem 'turbolinks', '~> 5.1'
gem 'trailblazer'
gem 'trailblazer-rails'
gem 'uglifier', '~> 4.1.10'
gem 'validate_url'
gem 'valid_email2'
gem 'webpacker', '~> 2.0'

group :development do
  #gem 'brakeman', :require => false
  #gem 'lol_dba'
  #gem 'seed_dump'
  #gem 'sdoc', '~> 0.4.0'
  gem 'web-console'
  gem 'table_print'
  gem 'listen'
end

group :development, :test do
  gem 'byebug'
  gem 'ffaker'
  #gem 'rspec-cells'
  #gem 'rspec-rails', '~> 3.6'
  #gem 'rspec-kickstarter'



  gem 'oauth2'
  gem 'parallel_tests'
  gem 'spring'

end

group :test do
  #gem 'factory_bot_rails'
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
  gem 'webmock'
  gem 'minitest-reporters'
  gem 'm', '~> 1.5.0'
  #gem 'capybara-email'
  #gem 'capybara-screenshot'
  #gem 'database_cleaner'
  #gem 'launchy'
  #gem 'nokogiri' #, '~> 1.8'
  #gem 'pundit-matchers', git: 'https://github.com/crowdAI/pundit-matchers'
  #gem 'rails-controller-testing'
  #gem 'rspec-retry'
  #gem 'simplecov', :require => false
  #gem 'selenium-webdriver'
  #gem 'timecop'
end
