require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DockerFilesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DockerFile. As you add validations to DockerFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DockerFilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all docker_files as @docker_files" do
      docker_file = DockerFile.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:docker_files)).to eq([docker_file])
    end
  end

  describe "GET #show" do
    it "assigns the requested docker_file as @docker_file" do
      docker_file = DockerFile.create! valid_attributes
      get :show, {:id => docker_file.to_param}, valid_session
      expect(assigns(:docker_file)).to eq(docker_file)
    end
  end

  describe "GET #new" do
    it "assigns a new docker_file as @docker_file" do
      get :new, {}, valid_session
      expect(assigns(:docker_file)).to be_a_new(DockerFile)
    end
  end

  describe "GET #edit" do
    it "assigns the requested docker_file as @docker_file" do
      docker_file = DockerFile.create! valid_attributes
      get :edit, {:id => docker_file.to_param}, valid_session
      expect(assigns(:docker_file)).to eq(docker_file)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DockerFile" do
        expect {
          post :create, {:docker_file => valid_attributes}, valid_session
        }.to change(DockerFile, :count).by(1)
      end

      it "assigns a newly created docker_file as @docker_file" do
        post :create, {:docker_file => valid_attributes}, valid_session
        expect(assigns(:docker_file)).to be_a(DockerFile)
        expect(assigns(:docker_file)).to be_persisted
      end

      it "redirects to the created docker_file" do
        post :create, {:docker_file => valid_attributes}, valid_session
        expect(response).to redirect_to(DockerFile.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved docker_file as @docker_file" do
        post :create, {:docker_file => invalid_attributes}, valid_session
        expect(assigns(:docker_file)).to be_a_new(DockerFile)
      end

      it "re-renders the 'new' template" do
        post :create, {:docker_file => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested docker_file" do
        docker_file = DockerFile.create! valid_attributes
        put :update, {:id => docker_file.to_param, :docker_file => new_attributes}, valid_session
        docker_file.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested docker_file as @docker_file" do
        docker_file = DockerFile.create! valid_attributes
        put :update, {:id => docker_file.to_param, :docker_file => valid_attributes}, valid_session
        expect(assigns(:docker_file)).to eq(docker_file)
      end

      it "redirects to the docker_file" do
        docker_file = DockerFile.create! valid_attributes
        put :update, {:id => docker_file.to_param, :docker_file => valid_attributes}, valid_session
        expect(response).to redirect_to(docker_file)
      end
    end

    context "with invalid params" do
      it "assigns the docker_file as @docker_file" do
        docker_file = DockerFile.create! valid_attributes
        put :update, {:id => docker_file.to_param, :docker_file => invalid_attributes}, valid_session
        expect(assigns(:docker_file)).to eq(docker_file)
      end

      it "re-renders the 'edit' template" do
        docker_file = DockerFile.create! valid_attributes
        put :update, {:id => docker_file.to_param, :docker_file => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested docker_file" do
      docker_file = DockerFile.create! valid_attributes
      expect {
        delete :destroy, {:id => docker_file.to_param}, valid_session
      }.to change(DockerFile, :count).by(-1)
    end

    it "redirects to the docker_files list" do
      docker_file = DockerFile.create! valid_attributes
      delete :destroy, {:id => docker_file.to_param}, valid_session
      expect(response).to redirect_to(docker_files_url)
    end
  end

end
