# == Schema Information
#
# Table name: hosting_institutions
#
#  id             :integer          not null, primary key
#  institution    :string
#  address        :text
#  description    :text
#  contact_person :string
#  contact_phone  :string
#  contact_email  :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HostingInstitutionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # HostingInstitution. As you add validations to HostingInstitution, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HostingInstitutionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all hosting_institutions as @hosting_institutions" do
      hosting_institution = HostingInstitution.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:hosting_institutions)).to eq([hosting_institution])
    end
  end

  describe "GET #show" do
    it "assigns the requested hosting_institution as @hosting_institution" do
      hosting_institution = HostingInstitution.create! valid_attributes
      get :show, {:id => hosting_institution.to_param}, valid_session
      expect(assigns(:hosting_institution)).to eq(hosting_institution)
    end
  end

  describe "GET #new" do
    it "assigns a new hosting_institution as @hosting_institution" do
      get :new, {}, valid_session
      expect(assigns(:hosting_institution)).to be_a_new(HostingInstitution)
    end
  end

  describe "GET #edit" do
    it "assigns the requested hosting_institution as @hosting_institution" do
      hosting_institution = HostingInstitution.create! valid_attributes
      get :edit, {:id => hosting_institution.to_param}, valid_session
      expect(assigns(:hosting_institution)).to eq(hosting_institution)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new HostingInstitution" do
        expect {
          post :create, {:hosting_institution => valid_attributes}, valid_session
        }.to change(HostingInstitution, :count).by(1)
      end

      it "assigns a newly created hosting_institution as @hosting_institution" do
        post :create, {:hosting_institution => valid_attributes}, valid_session
        expect(assigns(:hosting_institution)).to be_a(HostingInstitution)
        expect(assigns(:hosting_institution)).to be_persisted
      end

      it "redirects to the created hosting_institution" do
        post :create, {:hosting_institution => valid_attributes}, valid_session
        expect(response).to redirect_to(HostingInstitution.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved hosting_institution as @hosting_institution" do
        post :create, {:hosting_institution => invalid_attributes}, valid_session
        expect(assigns(:hosting_institution)).to be_a_new(HostingInstitution)
      end

      it "re-renders the 'new' template" do
        post :create, {:hosting_institution => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hosting_institution" do
        hosting_institution = HostingInstitution.create! valid_attributes
        put :update, {:id => hosting_institution.to_param, :hosting_institution => new_attributes}, valid_session
        hosting_institution.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested hosting_institution as @hosting_institution" do
        hosting_institution = HostingInstitution.create! valid_attributes
        put :update, {:id => hosting_institution.to_param, :hosting_institution => valid_attributes}, valid_session
        expect(assigns(:hosting_institution)).to eq(hosting_institution)
      end

      it "redirects to the hosting_institution" do
        hosting_institution = HostingInstitution.create! valid_attributes
        put :update, {:id => hosting_institution.to_param, :hosting_institution => valid_attributes}, valid_session
        expect(response).to redirect_to(hosting_institution)
      end
    end

    context "with invalid params" do
      it "assigns the hosting_institution as @hosting_institution" do
        hosting_institution = HostingInstitution.create! valid_attributes
        put :update, {:id => hosting_institution.to_param, :hosting_institution => invalid_attributes}, valid_session
        expect(assigns(:hosting_institution)).to eq(hosting_institution)
      end

      it "re-renders the 'edit' template" do
        hosting_institution = HostingInstitution.create! valid_attributes
        put :update, {:id => hosting_institution.to_param, :hosting_institution => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested hosting_institution" do
      hosting_institution = HostingInstitution.create! valid_attributes
      expect {
        delete :destroy, {:id => hosting_institution.to_param}, valid_session
      }.to change(HostingInstitution, :count).by(-1)
    end

    it "redirects to the hosting_institutions list" do
      hosting_institution = HostingInstitution.create! valid_attributes
      delete :destroy, {:id => hosting_institution.to_param}, valid_session
      expect(response).to redirect_to(hosting_institutions_url)
    end
  end

end
