# == Schema Information
#
# Table name: timelines
#
#  id             :integer          not null, primary key
#  challenge_id :integer
#  seq            :integer
#  event          :string
#  event_time     :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TimelinesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Timeline. As you add validations to Timeline, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TimelinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all timelines as @timelines" do
      timeline = Timeline.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:timelines)).to eq([timeline])
    end
  end

  describe "GET #show" do
    it "assigns the requested timeline as @timeline" do
      timeline = Timeline.create! valid_attributes
      get :show, {:id => timeline.to_param}, valid_session
      expect(assigns(:timeline)).to eq(timeline)
    end
  end

  describe "GET #new" do
    it "assigns a new timeline as @timeline" do
      get :new, {}, valid_session
      expect(assigns(:timeline)).to be_a_new(Timeline)
    end
  end

  describe "GET #edit" do
    it "assigns the requested timeline as @timeline" do
      timeline = Timeline.create! valid_attributes
      get :edit, {:id => timeline.to_param}, valid_session
      expect(assigns(:timeline)).to eq(timeline)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Timeline" do
        expect {
          post :create, {:timeline => valid_attributes}, valid_session
        }.to change(Timeline, :count).by(1)
      end

      it "assigns a newly created timeline as @timeline" do
        post :create, {:timeline => valid_attributes}, valid_session
        expect(assigns(:timeline)).to be_a(Timeline)
        expect(assigns(:timeline)).to be_persisted
      end

      it "redirects to the created timeline" do
        post :create, {:timeline => valid_attributes}, valid_session
        expect(response).to redirect_to(Timeline.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved timeline as @timeline" do
        post :create, {:timeline => invalid_attributes}, valid_session
        expect(assigns(:timeline)).to be_a_new(Timeline)
      end

      it "re-renders the 'new' template" do
        post :create, {:timeline => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested timeline" do
        timeline = Timeline.create! valid_attributes
        put :update, {:id => timeline.to_param, :timeline => new_attributes}, valid_session
        timeline.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested timeline as @timeline" do
        timeline = Timeline.create! valid_attributes
        put :update, {:id => timeline.to_param, :timeline => valid_attributes}, valid_session
        expect(assigns(:timeline)).to eq(timeline)
      end

      it "redirects to the timeline" do
        timeline = Timeline.create! valid_attributes
        put :update, {:id => timeline.to_param, :timeline => valid_attributes}, valid_session
        expect(response).to redirect_to(timeline)
      end
    end

    context "with invalid params" do
      it "assigns the timeline as @timeline" do
        timeline = Timeline.create! valid_attributes
        put :update, {:id => timeline.to_param, :timeline => invalid_attributes}, valid_session
        expect(assigns(:timeline)).to eq(timeline)
      end

      it "re-renders the 'edit' template" do
        timeline = Timeline.create! valid_attributes
        put :update, {:id => timeline.to_param, :timeline => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested timeline" do
      timeline = Timeline.create! valid_attributes
      expect {
        delete :destroy, {:id => timeline.to_param}, valid_session
      }.to change(Timeline, :count).by(-1)
    end

    it "redirects to the timelines list" do
      timeline = Timeline.create! valid_attributes
      delete :destroy, {:id => timeline.to_param}, valid_session
      expect(response).to redirect_to(timelines_url)
    end
  end

  # === Routes (REST) ===
  it { should route(:get, '/challenges/1/timelines/new').to('timelines#new', {:challenge_id=>"1"}) }
  it { should route(:get, '/challenges/1/timelines').to('timelines#index', {:challenge_id=>"1"}) }
  it { should route(:patch, '/challenges/1/timelines/1').to('timelines#update', {:challenge_id=>"1", :id=>"1"}) }
  it { should route(:post, '/challenges/1/timelines').to('timelines#create', {:challenge_id=>"1"}) }
  it { should route(:get, '/challenges/1/timelines/1/edit').to('timelines#edit', {:challenge_id=>"1", :id=>"1"}) }
  it { should route(:delete, '/challenges/1/timelines/1').to('timelines#destroy', {:challenge_id=>"1", :id=>"1"}) }
  it { should route(:get, '/challenges/1/timelines/1').to('timelines#show', {:challenge_id=>"1", :id=>"1"}) }
  # === Callbacks (Before) ===
  it { should use_before_filter(:verify_authenticity_token) }
  it { should use_before_filter(:set_xhr_redirected_to) }
  it { should use_before_filter(:set_request_method_cookie) }
  it { should use_before_filter(:authenticate_user!) }
  it { should use_before_filter(:configure_permitted_parameters) }
  it { should use_before_filter(:set_timeline) }
  # === Callbacks (After) ===
  it { should use_after_filter(:abort_xdomain_redirect) }
  it { should use_after_filter(:verify_same_origin_request) }
  # === Callbacks (Around) ===

end
